package blended.mgmt.app.theme

import blended.ui.components.reacttable.DefaultReactTableStyle
import blended.ui.themes.DefaultSideBarMenuTheme

object BlendedMgmtTheme extends DefaultSideBarMenuTheme

object BlendedMgmtTableStyle extends DefaultReactTableStyle